/* 
* Autogenerated interface code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package repositories;

import java.util.Collection;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import domain.Allergen;

@Repository
public interface AllergenRepository extends JpaRepository<Allergen, Integer>{
	
	@Query("select i.allergens from Ingredient i where i.id = ?1")
	Collection<Allergen> findAllergensByIngredientId(int ingredientId);

	@Query("select a from Allergen a where a.name = ?1")
	Allergen findAllergenByName(String allergenName);
	
	@Query("select a from Allergen a where a.users.size >= ALL(select a1.users.size from Allergen a1)")
	Collection<Allergen> allergenMoreUsers();

}
