/* 
* Autogenerated interface code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package repositories;

import java.util.Collection;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import domain.Assessment;

@Repository
public interface AssessmentRepository extends JpaRepository<Assessment, Integer>{
	
	@Query("select a from Assessment a where a.deleted = false")
	Collection<Assessment> findAllWithoutDelete();
	
}
