/* 
* Autogenerated interface code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import domain.Clerk;
import domain.User;

@Repository
public interface ClerkRepository extends JpaRepository<Clerk, Integer>{
	
	@Query("select a from Clerk a where a.userAccount.id = ?1")
	Clerk findByPrincipal(int userAccountId);
}
