/* 
* Autogenerated interface code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package repositories;

import java.util.Collection;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import domain.SalesOrder;
import domain.User;

@Repository
public interface SalesOrderRepository extends JpaRepository<SalesOrder, Integer>{
	
	@Query("select o from SalesOrder o where o.clerk = null")
	Collection<SalesOrder> findOrdersWithoutClerk();
	
	@Query("select o from SalesOrder o where o.clerk.id = ?1")
	Collection<SalesOrder> findOrdersByClerk(int clerkId);
	
	@Query("select o from SalesOrder o where o.subscription.id = (select s from Subscription s where s.user.id = ?1)")
	Collection<SalesOrder> findOrdersByUser(int userId);
	
	@Query("select o from SalesOrder o where o.sent = true")
	Integer getNumberOfSentOrders();
}
