/* 
* Autogenerated interface code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import domain.Substitutes;

@Repository
public interface SubstitutesRepository extends JpaRepository<Substitutes, Integer>{
	

}
