/* 
* Autogenerated converter code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package converters;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import repositories.SalesOrderRepository;
import domain.SalesOrder;

@Component
@Transactional
public class StringToSalesOrderConverter implements Converter<String, SalesOrder> {

	@Autowired
	SalesOrderRepository orderRepository;

	@Override
	public SalesOrder convert(String text) {
		SalesOrder result;
		int id;

		try {
			id = Integer.valueOf(text);
			result = orderRepository.findOne(id);
		} catch (Throwable oops) {
			throw new IllegalArgumentException(oops);
		}

		return result;
	}

}
