/* 
* Autogenerated converter code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package converters;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import repositories.SubstitutesRepository;
import domain.Substitutes;

@Component
@Transactional
public class StringToSubstitutesConverter implements Converter<String, Substitutes> {

	@Autowired
	SubstitutesRepository substitutesRepository;

	@Override
	public Substitutes convert(String text) {
		Substitutes result;
		int id;

		try {
			id = Integer.valueOf(text);
			result = substitutesRepository.findOne(id);
		} catch (Throwable oops) {
			throw new IllegalArgumentException(oops);
		}

		return result;
	}

}
