/* 
* Autogenerated converter code 
* Variables (text between %) must have been replaced when code is autogenerated
*/
package converters;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.convert.converter.Converter;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import repositories.AllergenRepository;
import domain.Allergen;

@Component
@Transactional
public class StringToAllergenConverter implements Converter<String, Allergen> {

	@Autowired
	AllergenRepository allergenRepository;

	@Override
	public Allergen convert(String text) {
		Allergen result;
		int id;

		try {
			id = Integer.valueOf(text);
			result = allergenRepository.findOne(id);
		} catch (Throwable oops) {
			throw new IllegalArgumentException(oops);
		}

		return result;
	}

}
