/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.ActorRepository;
import domain.Actor;

@Service
@Transactional
public class ActorService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private ActorRepository actorRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public ActorService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------

	public void save(Actor entity){
		Assert.notNull(entity);
		
		this.actorRepository.save(entity);
	}

	public void delete(Actor entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.actorRepository.exists(entity.getId()));
		
		this.actorRepository.delete( entity );
		
		Assert.isTrue(!this.actorRepository.exists(entity.getId()));
	}

	public Actor findOne(int id){
		Assert.isTrue(id != 0);
		
		Actor res;
		
		res = this.actorRepository.findOne(id);
		
		return res;
	}

	public Collection<Actor> findAll(){
		Collection<Actor> res;
		
		res = actorRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
