/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.AllergenRepository;
import domain.Allergen;

@Service
@Transactional
public class AllergenService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private AllergenRepository allergenRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public AllergenService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Allergen create(){
		Allergen newbye;
		
		newbye = new Allergen();
		
		return newbye;
	}

	public void save(Allergen entity){
		Assert.notNull(entity);
		
		this.allergenRepository.save(entity);
	}

	public void delete(Allergen entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.allergenRepository.exists(entity.getId()));
		
		this.allergenRepository.delete( entity );
		
		Assert.isTrue(!this.allergenRepository.exists(entity.getId()));
	}

	public Allergen findOne(int id){
		Assert.isTrue(id != 0);
		
		Allergen res;
		
		res = this.allergenRepository.findOne(id);
		
		return res;
	}

	public Collection<Allergen> findAll(){
		Collection<Allergen> res;
		
		res = allergenRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
