/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.AssessmentRepository;
import domain.Assessment;

@Service
@Transactional
public class AssessmentService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private AssessmentRepository assessmentRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public AssessmentService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Assessment create(){
		Assessment newbye;
		
		newbye = new Assessment();
		
		return newbye;
	}

	public void save(Assessment entity){
		Assert.notNull(entity);
		
		this.assessmentRepository.save(entity);
	}

	public void delete(Assessment entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.assessmentRepository.exists(entity.getId()));
		
		this.assessmentRepository.delete( entity );
		
		Assert.isTrue(!this.assessmentRepository.exists(entity.getId()));
	}

	public Assessment findOne(int id){
		Assert.isTrue(id != 0);
		
		Assessment res;
		
		res = this.assessmentRepository.findOne(id);
		
		return res;
	}

	public Collection<Assessment> findAll(){
		Collection<Assessment> res;
		
		res = assessmentRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
