/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.CategoryRepository;
import domain.Category;

@Service
@Transactional
public class CategoryService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private CategoryRepository categoryRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public CategoryService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Category create(){
		Category newbye;
		
		newbye = new Category();
		
		return newbye;
	}

	public void save(Category entity){
		Assert.notNull(entity);
		
		this.categoryRepository.save(entity);
	}

	public void delete(Category entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.categoryRepository.exists(entity.getId()));
		
		this.categoryRepository.delete( entity );
		
		Assert.isTrue(!this.categoryRepository.exists(entity.getId()));
	}

	public Category findOne(int id){
		Assert.isTrue(id != 0);
		
		Category res;
		
		res = this.categoryRepository.findOne(id);
		
		return res;
	}

	public Collection<Category> findAll(){
		Collection<Category> res;
		
		res = categoryRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
