/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.ClerkRepository;
import security.LoginService;
import security.UserAccount;
import domain.Clerk;
import domain.User;

@Service
@Transactional
public class ClerkService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private ClerkRepository clerkRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public ClerkService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Clerk create(){
		Clerk newbye;
		
		newbye = new Clerk();
		
		return newbye;
	}

	public void save(Clerk entity){
		Assert.notNull(entity);
		
		this.clerkRepository.save(entity);
	}

	public void delete(Clerk entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.clerkRepository.exists(entity.getId()));
		
		this.clerkRepository.delete( entity );
		
		Assert.isTrue(!this.clerkRepository.exists(entity.getId()));
	}

	public Clerk findOne(int id){
		Assert.isTrue(id != 0);
		
		Clerk res;
		
		res = this.clerkRepository.findOne(id);
		
		return res;
	}

	public Collection<Clerk> findAll(){
		Collection<Clerk> res;
		
		res = clerkRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	public Clerk findByPrincipal() {
	 	Clerk clerk;
	 	UserAccount userAccount;
	 	
	 	userAccount = LoginService.getPrincipal();
	 	clerk = clerkRepository.findByPrincipal(userAccount.getId());
	 	
	 	Assert.notNull(clerk);
	 	
	 	return clerk;
	}
	
	// Ancillary methods ------------------------------------------------------

}
