/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.MenuRepository;
import domain.Menu;

@Service
@Transactional
public class MenuService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private MenuRepository menuRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public MenuService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Menu create(){
		Menu newbye;
		
		newbye = new Menu();
		
		return newbye;
	}

	public void save(Menu entity){
		Assert.notNull(entity);
		
		this.menuRepository.save(entity);
	}

	public void delete(Menu entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.menuRepository.exists(entity.getId()));
		
		this.menuRepository.delete( entity );
		
		Assert.isTrue(!this.menuRepository.exists(entity.getId()));
	}

	public Menu findOne(int id){
		Assert.isTrue(id != 0);
		
		Menu res;
		
		res = this.menuRepository.findOne(id);
		
		return res;
	}

	public Collection<Menu> findAll(){
		Collection<Menu> res;
		
		res = menuRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
