/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.ArrayList;
import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.QuantityRepository;
import domain.Ingredient;
import domain.Quantity;
import domain.Recipe;

@Service
@Transactional
public class QuantityService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private QuantityRepository quantityRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public QuantityService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Quantity create(Ingredient ingredient, Recipe recipe){
		Quantity newbye;
		
		newbye = new Quantity();
		newbye.setIngredient(ingredient);
		newbye.setRecipe(recipe);	
		
		return newbye;
	}

	public void save(Quantity entity){
		Assert.notNull(entity);
		Recipe recipe;
		Ingredient ingredient;
		
		recipe = entity.getRecipe();
		ingredient = entity.getIngredient();
		
		recipe.getQuantities().add(entity);
		ingredient.getQuantities().add(entity);
		
		this.quantityRepository.save(entity);
	}

	public void delete(Quantity entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.quantityRepository.exists(entity.getId()));
		
		this.quantityRepository.delete( entity );
		
		Assert.isTrue(!this.quantityRepository.exists(entity.getId()));
	}

	public Quantity findOne(int id){
		Assert.isTrue(id != 0);
		
		Quantity res;
		
		res = this.quantityRepository.findOne(id);
		
		return res;
	}

	public Collection<Quantity> findAll(){
		Collection<Quantity> res;
		
		res = quantityRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
