/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.SalesOrderRepository;
import domain.SalesOrder;

@Service
@Transactional
public class SalesOrderService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private SalesOrderRepository orderRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public SalesOrderService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public SalesOrder create(){
		SalesOrder newbye;
		
		newbye = new SalesOrder();
		
		return newbye;
	}

	public void save(SalesOrder entity){
		Assert.notNull(entity);
		
		this.orderRepository.save(entity);
	}

	public void delete(SalesOrder entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.orderRepository.exists(entity.getId()));
		
		this.orderRepository.delete( entity );
		
		Assert.isTrue(!this.orderRepository.exists(entity.getId()));
	}

	public SalesOrder findOne(int id){
		Assert.isTrue(id != 0);
		
		SalesOrder res;
		
		res = this.orderRepository.findOne(id);
		
		return res;
	}

	public Collection<SalesOrder> findAll(){
		Collection<SalesOrder> res;
		
		res = orderRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
