/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.SubscriptionRepository;
import domain.Subscription;

@Service
@Transactional
public class SubscriptionService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private SubscriptionRepository subscriptionRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public SubscriptionService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Subscription create(){
		Subscription newbye;
		
		newbye = new Subscription();
		
		return newbye;
	}

	public void save(Subscription entity){
		Assert.notNull(entity);
		
		this.subscriptionRepository.save(entity);
	}

	public void delete(Subscription entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.subscriptionRepository.exists(entity.getId()));
		
		this.subscriptionRepository.delete( entity );
		
		Assert.isTrue(!this.subscriptionRepository.exists(entity.getId()));
	}

	public Subscription findOne(int id){
		Assert.isTrue(id != 0);
		
		Subscription res;
		
		res = this.subscriptionRepository.findOne(id);
		
		return res;
	}

	public Collection<Subscription> findAll(){
		Collection<Subscription> res;
		
		res = subscriptionRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
