/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.SubstitutesRepository;
import domain.SalesOrder;
import domain.Substitutes;

@Service
@Transactional
public class SubstitutesService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private SubstitutesRepository substitutesRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public SubstitutesService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public Substitutes create(SalesOrder order){
		Substitutes newbye;
		
		newbye = new Substitutes();
		
		newbye.setOrder(order);
		
		return newbye;
	}

	public void save(Substitutes entity){
		Assert.notNull(entity);
		
		this.substitutesRepository.save(entity);
	}

	public Substitutes findOne(int id){
		Assert.isTrue(id != 0);
		
		Substitutes res;
		
		res = this.substitutesRepository.findOne(id);
		
		return res;
	}

	public Collection<Substitutes> findAll(){
		Collection<Substitutes> res;
		
		res = substitutesRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
