/* 
* Autogenerated service code 
* Variables (text between %) must have been replaced when code is autogenerated
*/

package services;

import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.Assert;

import repositories.UserRepository;
import domain.User;

@Service
@Transactional
public class UserService {

	// Managed repository -----------------------------------------------------
	@Autowired
	private UserRepository userRepository;

	// Ancillary services -----------------------------------------------------

	// Constructor ------------------------------------------------------------
	public UserService(){
		super();
	}

	// Simple CRUD methods ----------------------------------------------------
	public User create(){
		User newbye;
		
		newbye = new User();
		
		return newbye;
	}

	public void save(User entity){
		Assert.notNull(entity);
		
		this.userRepository.save(entity);
	}

	public void delete(User entity){
		Assert.isTrue(entity.getId()!=0);
		Assert.isTrue(this.userRepository.exists(entity.getId()));
		
		this.userRepository.delete( entity );
		
		Assert.isTrue(!this.userRepository.exists(entity.getId()));
	}

	public User findOne(int id){
		Assert.isTrue(id != 0);
		
		User res;
		
		res = this.userRepository.findOne(id);
		
		return res;
	}

	public Collection<User> findAll(){
		Collection<User> res;
		
		res = userRepository.findAll();
		
		return res;
	}

	// Other business methods -------------------------------------------------

	// Ancillary methods ------------------------------------------------------

}
